#!/usr/bin/env bash

set -euo pipefail

#scriptname=sh-treebox-ci
unset LOG INIT_LOG CWD U_S

: "${CWD:="$PWD"}"

: "${U_S:="$PWD/vnd/dotmpe/user-scripts"}"
: "${sh_tools:="$U_S/tools/sh"}"
: "${LOG:="$sh_tools/log.sh"}"
: "${INIT_LOG:="$LOG"}"

. "tools/ci/before-install.sh"
. "tools/ci/install.sh"

. "tools/ci/before.sh"

. "tools/ci/script.sh" || sh_ci_script_status=$?

. "tools/ci/before-cache.sh"

if test $sh_ci_script_status -eq 0
then
  TRAVIS_TEST_RESULT=1
  . "tools/ci/after-success.sh"
else
  TRAVIS_TEST_RESULT=0
  . "tools/ci/after-failure.sh"
fi

. "tools/ci/after.sh"

ci_announce "$scriptname OK"
# Copy: U-S:
