#!/usr/bin/env bash

# Shell script wrapper for $PWD/sh-* scripts and other project/CI tooling


run()
{
  "$@"
}

run-cmd()
{
  print_yellow "" "Running $SCRIPT_SHELL -c '$*'..."
  $SCRIPT_SHELL -c "$@" &&
    print_green "OK" "Command $SCRIPT_SHELL -c '$*'" ||
    print_red "Not OK: $?" "Command $SCRIPT_SHELL -c '$*'"
}

spec()
{
  test $# -gt 0 || set -- sh-baseline.tab "*/bin/u-s *"

  . "$U_S/tools/ci/parts/std-stack.sh"
  . "$U_S/tools/ci/parts/std-runner.sh"

  sh_spec "$1" | grep -v '^\s*\(#.*\|\s*\)$' | while read scriptline
  do
    fnmatch "$2" "$scriptline" || continue
    run-cmd "$scriptline" </dev/tty
  done
}


set -euo pipefail

. "${sh_tools:="$PWD/tools/sh"}/env.sh"

test $# -gt 0 || set -- spec sh-baseline.tab '*'

print_yellow "" "Starting '$*'"
test -e "$1" && {

  $SCRIPT_SHELL \
    "$@" && print_green "" "Completed '$*'" || print_red "" "Failed '$*'"

} || {

  "$@" && print_green "" "Completed '$*'" || print_red "" "Failed '$*'"
}

# vim:ft=bash:
