#!/bin/sh

# Keep build tooling copies in sync

remove_dupes() # ~
{
  awk '!a[$0]++'
}

unique_files() # PATHNAME...
{
  for path in "$@"
  do
    test -e "$path" && realpath "$path" || echo "$path"
  done | remove_dupes
}

diff_files() # FILEPATH PATHNAME...
{
  local from="$1"
  shift
  for path in "$@"
  do
    test -f "$path" || path="$path/$1"
    diff -bqr "$1" "$path" && continue
  done
}

set -e

for x in .travis.yml sh-* tools/ci/*.sh tools/sh/parts/*.sh
do
  vimdiff ~/bin/$x ~/project/user-scripts*/$x $x
  continue
done
