#!/usr/bin/env bash

# Keep build tooling copies in sync
# (x-ci/sh-sync, depends on BIN:sh-sync, depends on compsure user-includes).

for x in .travis.yml sh-* \
  tools/ci/*.sh tools/ci/parts/*.sh \
  tools/sh/*.sh \
  tools/sh/parts/*.sh
do
	files-sync ~/bin/$x ~/project/user-scripts*/$x $x && c-passed || c-failed
done

# Id: xi-ci/ sh-sync
# From: BIN:
# To: HT:
